language: python
python:
  - 2.7
install:
- pip install tox
script:
 - tox -v -e py
after_success:
 - codecov
deploy:
  provider: pypi
  user: sagersmith8
  password:
    secure: PYPI_PW
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 2.7
