language: python
python:
  - 2.7
install:
- pip install tox-travis
script:
 - git config --global user.email "sagersmith8@.com"
 - git config --global user.name "Sage Smith"
 - tox -v -e py
after_success:
 - codecov
deploy:
  provider: pypi
  user: sagersmith8
  password:
    secure: PYPI_PW
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 2.7
