language: python
python:
  - 2.7
install:
- pip install tox-travis
- pip install codecov
script:
 - tox -v -e py
after_success:
 - codecov
 if: branch = master
   - git config --global user.email "builds@travis-ci.com"
   - git config --global user.name "Travis CI"
   - export GIT_TAG=0.0.$TRAVIS_BUILD_NUMBER
   - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
   - git push -q https://${GIT_TOKEN}@github.com/sagersmith8/journal --tags
   - ls -R

branches:
  only:
    - master
deploy:
  provider: pypi
  user: sagersmith8
  password: $PYPI_PW
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 2.7
